export const CHAINS = {
        btc: {
                name: 'Bitcoin',
                symbol: 'BTC',
                emoji: '<:coin_btc:1516859667093917877>',
                decimals: 8,
                tatumNetwork: 'bitcoin',
                addressType: 'utxo',
                explorer: 'https://blockchair.com/bitcoin/address/',
                txExplorer: 'https://blockchair.com/bitcoin/transaction/',
        },
        eth: {
                name: 'Ethereum',
                symbol: 'ETH',
                emoji: '<:coin_eth:1516859671057666071>',
                decimals: 18,
                tatumNetwork: 'ethereum',
                addressType: 'evm',
                explorer: 'https://etherscan.io/address/',
                txExplorer: 'https://etherscan.io/tx/',
        },
        ltc: {
                name: 'Litecoin',
                symbol: 'LTC',
                emoji: '<:coin_ltc:1516859796731461663>',
                decimals: 8,
                tatumNetwork: 'litecoin',
                addressType: 'utxo',
                explorer: 'https://blockchair.com/litecoin/address/',
                txExplorer: 'https://blockchair.com/litecoin/transaction/',
        },
        bch: {
                name: 'Bitcoin Cash',
                symbol: 'BCH',
                emoji: '<:coin_bch:1516859774195728516>',
                decimals: 8,
                tatumNetwork: 'bcash',
                addressType: 'utxo',
                explorer: 'https://blockchair.com/bitcoin-cash/address/',
                txExplorer: 'https://blockchair.com/bitcoin-cash/transaction/',
        },
        doge: {
                name: 'Dogecoin',
                symbol: 'DOGE',
                emoji: '<:coin_doge:1516859711746736191>',
                decimals: 8,
                tatumNetwork: 'dogecoin',
                addressType: 'utxo',
                explorer: 'https://blockchair.com/dogecoin/address/',
                txExplorer: 'https://blockchair.com/dogecoin/transaction/',
        },
        zec: {
                name: 'Zcash',
                symbol: 'ZEC',
                emoji: '<:coin_zec:1516859729832316999>',
                decimals: 8,
                tatumNetwork: 'zcash',
                addressType: 'utxo',
                explorer: 'https://blockchair.com/zcash/address/',
                txExplorer: 'https://blockchair.com/zcash/transaction/',
        },
        dash: {
                name: 'Dash',
                symbol: 'DASH',
                emoji: '<:coin_dash:1516860162877690027>',
                decimals: 8,
                tatumNetwork: 'dash',
                addressType: 'utxo',
                explorer: 'https://blockchair.com/dash/address/',
                txExplorer: 'https://blockchair.com/dash/transaction/',
        },
        xrp: {
                name: 'XRP',
                symbol: 'XRP',
                emoji: '<:coin_xrp:1516859684672372831>',
                decimals: 6,
                tatumNetwork: 'xrp',
                addressType: 'xrp',
                explorer: 'https://xrpscan.com/account/',
                txExplorer: 'https://xrpscan.com/tx/',
        },
        xlm: {
                name: 'Stellar',
                symbol: 'XLM',
                emoji: '<:coin_xlm:1516859734379069722>',
                decimals: 7,
                tatumNetwork: 'xlm',
                addressType: 'xlm',
                explorer: 'https://stellar.expert/explorer/public/account/',
                txExplorer: 'https://stellar.expert/explorer/public/tx/',
        },
        trx: {
                name: 'Tron',
                symbol: 'TRX',
                emoji: '<:coin_trx:1516859698245271732>',
                decimals: 6,
                tatumNetwork: 'tron',
                addressType: 'tron',
                explorer: 'https://tronscan.org/#/address/',
                txExplorer: 'https://tronscan.org/#/transaction/',
        },
        sol: {
                name: 'Solana',
                symbol: 'SOL',
                emoji: '<:coin_sol:1516859693950042212>',
                decimals: 9,
                tatumNetwork: 'solana',
                addressType: 'solana',
                explorer: 'https://solscan.io/account/',
                txExplorer: 'https://solscan.io/tx/',
        },
        bnb: {
                name: 'BNB Chain',
                symbol: 'BNB',
                emoji: '<:coin_bnb:1516859680289460287>',
                decimals: 18,
                tatumNetwork: 'bsc',
                addressType: 'evm',
                explorer: 'https://bscscan.com/address/',
                txExplorer: 'https://bscscan.com/tx/',
        },
        pol: {
                name: 'Polygon',
                symbol: 'POL',
                emoji: '<:coin_pol:1516860022683078787>',
                decimals: 18,
                tatumNetwork: 'polygon',
                addressType: 'evm',
                explorer: 'https://polygonscan.com/address/',
                txExplorer: 'https://polygonscan.com/tx/',
        },
        avax: {
                name: 'Avalanche',
                symbol: 'AVAX',
                emoji: '<:coin_avax:1516859814540742886>',
                decimals: 18,
                tatumNetwork: 'avax',
                addressType: 'evm',
                explorer: 'https://snowtrace.io/address/',
                txExplorer: 'https://snowtrace.io/tx/',
        },
        algo: {
                name: 'Algorand',
                symbol: 'ALGO',
                emoji: '<:coin_algo:1516860003850522745>',
                decimals: 6,
                tatumNetwork: 'algorand',
                addressType: 'algorand',
                explorer: 'https://algoexplorer.io/address/',
                txExplorer: 'https://algoexplorer.io/tx/',
        },
        ada: {
                name: 'Cardano',
                symbol: 'ADA',
                emoji: '<:coin_ada:1516859747964551178>',
                decimals: 6,
                tatumNetwork: 'ada',
                addressType: 'ada',
                explorer: 'https://cardanoscan.io/address/',
                txExplorer: 'https://cardanoscan.io/transaction/',
        },
        xtz: {
                name: 'Tezos',
                symbol: 'XTZ',
                emoji: '<:coin_xtz:1516860452569616404>',
                decimals: 6,
                tatumNetwork: 'tezos',
                addressType: 'tezos',
                explorer: 'https://tzstats.com/',
                txExplorer: 'https://tzstats.com/',
        },
        xmr: {
                name: 'Monero',
                symbol: 'XMR',
                emoji: '<:coin_xmr:1516859752674758795>',
                decimals: 12,
                tatumNetwork: null,
                addressType: null,
                explorer: 'https://xmrchain.net/search?value=',
                txExplorer: 'https://xmrchain.net/tx/',
        },
        dot: {
                name: 'Polkadot',
                symbol: 'DOT',
                emoji: '<:coin_dot:1516859887131427040>',
                decimals: 10,
                tatumNetwork: 'dot',
                addressType: 'substrate',
                explorer: 'https://polkadot.subscan.io/account/',
                txExplorer: 'https://polkadot.subscan.io/extrinsic/',
        },
        near: {
                name: 'NEAR',
                symbol: 'NEAR',
                emoji: '<:coin_near:1516859810170015744>',
                decimals: 24,
                tatumNetwork: 'near',
                addressType: 'near',
                explorer: 'https://nearblocks.io/address/',
                txExplorer: 'https://nearblocks.io/txns/',
        },
        flr: {
                name: 'Flare',
                symbol: 'FLR',
                emoji: '<:coin_flr:1516860063942443088>',
                decimals: 18,
                tatumNetwork: 'flare',
                addressType: 'evm',
                explorer: 'https://flare-explorer.flare.network/address/',
                txExplorer: 'https://flare-explorer.flare.network/tx/',
        },
        kaia: {
                name: 'Kaia',
                symbol: 'KAIA',
                emoji: '<:coin_kaia:1516860606886580414>',
                decimals: 18,
                tatumNetwork: 'klaytn',
                addressType: 'evm',
                explorer: 'https://kaiascope.com/address/',
                txExplorer: 'https://kaiascope.com/tx/',
        },
        cro: {
                name: 'Cronos',
                symbol: 'CRO',
                emoji: '<:coin_cro:1516859823612887111>',
                decimals: 18,
                tatumNetwork: 'cro',
                addressType: 'evm',
                explorer: 'https://cronoscan.com/address/',
                txExplorer: 'https://cronoscan.com/tx/',
        },
        arb: {
                name: 'Arbitrum',
                symbol: 'ARB',
                emoji: '<:coin_arb:1516860096791969933>',
                decimals: 18,
                tatumNetwork: 'arbitrum',
                addressType: 'evm',
                explorer: 'https://arbiscan.io/address/',
                txExplorer: 'https://arbiscan.io/tx/',
        },
        op: {
                name: 'Optimism',
                symbol: 'OP',
                emoji: '<:coin_op:1516860571763478578>',
                decimals: 18,
                tatumNetwork: 'optimism',
                addressType: 'evm',
                explorer: 'https://optimistic.etherscan.io/address/',
                txExplorer: 'https://optimistic.etherscan.io/tx/',
        },
        inj: {
                name: 'Injective',
                symbol: 'INJ',
                emoji: '<:coin_inj:1516860110650216500>',
                decimals: 18,
                tatumNetwork: 'inj',
                addressType: 'evm',
                explorer: 'https://explorer.injective.network/account/',
                txExplorer: 'https://explorer.injective.network/transaction/',
        },
        sui: {
                name: 'Sui',
                symbol: 'SUI',
                emoji: '<:coin_sui:1516859800850530327>',
                decimals: 9,
                tatumNetwork: 'sui',
                addressType: 'sui',
                explorer: 'https://suivision.xyz/address/',
                txExplorer: 'https://suivision.xyz/txblock/',
        },
        apt: {
                name: 'Aptos',
                symbol: 'APT',
                emoji: '<:coin_apt:1516860090966212629>',
                decimals: 8,
                tatumNetwork: 'aptos',
                addressType: 'aptos',
                explorer: 'https://aptoscan.com/account/',
                txExplorer: 'https://aptoscan.com/transaction/',
        },
        sei: {
                name: 'Sei',
                symbol: 'SEI',
                emoji: '<:coin_sei:1516860350836768930>',
                decimals: 6,
                tatumNetwork: 'sei',
                addressType: 'sei',
                explorer: 'https://seistream.app/address/',
                txExplorer: 'https://seistream.app/tx/',
        },
        mnt: {
                name: 'Mantle',
                symbol: 'MNT',
                emoji: '<:coin_mnt:1516859882265903107>',
                decimals: 18,
                tatumNetwork: 'mantle',
                addressType: 'evm',
                explorer: 'https://mantlescan.xyz/address/',
                txExplorer: 'https://mantlescan.xyz/tx/',
        },
        hbar: {
                name: 'Hedera',
                symbol: 'HBAR',
                emoji: '<:coin_hbar:1516859792373710848>',
                decimals: 8,
                tatumNetwork: 'hbar',
                addressType: 'hbar',
                explorer: 'https://hashscan.io/mainnet/account/',
                txExplorer: 'https://hashscan.io/mainnet/transaction/',
        },
        kcs: {
                name: 'KuCoin',
                symbol: 'KCS',
                emoji: '<:coin_kcs:1516859969763541175>',
                decimals: 18,
                tatumNetwork: 'kcs',
                addressType: 'evm',
                explorer: 'https://explorer.kcc.io/address/',
                txExplorer: 'https://explorer.kcc.io/tx/',
        },

        // ── Tokens ──────────────────────────────────────────────────────────
        usdt:      { name: 'Tether USD',            symbol: 'USDT',      emoji: '<:coin_usdt:1516859675935510548>',      decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7', txExplorer: null },
        usdc:      { name: 'USD Coin',               symbol: 'USDC',      emoji: '<:coin_usdc:1516859689395163368>',      decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', txExplorer: null },
        usds:      { name: 'USDS',                   symbol: 'USDS',      emoji: '<:coin_usds:1516859716225994873>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        rain:      { name: 'Rain',                   symbol: 'RAIN',      emoji: '<:coin_rain:1516859721082994698>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        leo:       { name: 'LEO Token',              symbol: 'LEO',       emoji: '<:coin_leo:1516859725466177700>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        wbt:       { name: 'WhiteBIT Coin',          symbol: 'WBT',       emoji: '<:coin_wbt:1516859738485166083>',       decimals: 8,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        link:      { name: 'Chainlink',              symbol: 'LINK',      emoji: '<:coin_link:1516859756902481951>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/token/0x514910771af9ca656af840dff83e8264ecf986ca', txExplorer: null },
        usd1:      { name: 'USD1',                   symbol: 'USD1',      emoji: '<:coin_usd1:1516859761126150234>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        usde:      { name: 'USDe',                   symbol: 'USDe',      emoji: '<:coin_usde:1516859765689421875>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        gram:      { name: 'Gram',                   symbol: 'GRAM',      emoji: '<:coin_gram:1516859770118602904>',      decimals: 9,  tatumNetwork: null, addressType: null, explorer: 'https://tonscan.org/address/', txExplorer: null },
        dai:       { name: 'Dai',                    symbol: 'DAI',       emoji: '<:coin_dai:1516859778930839612>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f', txExplorer: null },
        lab:       { name: 'LAB',                    symbol: 'LAB',       emoji: '<:coin_lab:1516859783473397921>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        m:         { name: 'M',                      symbol: 'M',         emoji: '<:coin_m:1516859787805982781>',         decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        usyc:      { name: 'USYC',                   symbol: 'USYC',      emoji: '<:coin_usyc:1516859805715661050>',      decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        shib:      { name: 'Shiba Inu',              symbol: 'SHIB',      emoji: '<:coin_shib:1516859818596499468>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/token/0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce', txExplorer: null },
        usdg:      { name: 'USDG',                   symbol: 'USDG',      emoji: '<:coin_usdg:1516859828138414222>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        pyusd:     { name: 'PayPal USD',             symbol: 'PYUSD',     emoji: '<:coin_pyusd:1516859832433512680>',     decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        xaut:      { name: 'Tether Gold',            symbol: 'XAUt',      emoji: '<:coin_xaut:1516859837219209358>',      decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        buidl:     { name: 'BUIDL',                  symbol: 'BUIDL',     emoji: '<:coin_buidl:1516859845712547960>',     decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        wld:       { name: 'Worldcoin',              symbol: 'WLD',       emoji: '<:coin_wld:1516859849969762558>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        usdy:      { name: 'USDY',                   symbol: 'USDY',      emoji: '<:coin_usdy:1516859854407340212>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        uni:       { name: 'Uniswap',                symbol: 'UNI',       emoji: '<:coin_uni:1516859859298029619>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/token/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984', txExplorer: null },
        aster:     { name: 'Aster DeFi',             symbol: 'ASTER',     emoji: '<:coin_aster:1516859864062758942>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        paxg:      { name: 'PAX Gold',               symbol: 'PAXG',      emoji: '<:coin_paxg:1516859868760375396>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        wlfi:      { name: 'World Liberty Fi',       symbol: 'WLFI',      emoji: '<:coin_wlfi:1516859873005015076>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        ondo:      { name: 'Ondo Finance',           symbol: 'ONDO',      emoji: '<:coin_ondo:1516859877946036407>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        rlusd:     { name: 'Ripple USD',             symbol: 'RLUSD',     emoji: '<:coin_rlusd:1516859891665600522>',     decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://xrpscan.com/account/', txExplorer: null },
        okb:       { name: 'OKB',                    symbol: 'OKB',       emoji: '<:coin_okb:1516859896312889476>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        htx:       { name: 'HTX',                    symbol: 'HTX',       emoji: '<:coin_htx:1516859900964245604>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        usdf:      { name: 'USDF',                   symbol: 'USDF',      emoji: '<:coin_usdf:1516859905385037945>',      decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        usdd:      { name: 'USDD',                   symbol: 'USDD',      emoji: '<:coin_usdd:1516859914423898242>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://tronscan.org/#/address/', txExplorer: null },
        sky:       { name: 'Sky',                    symbol: 'SKY',       emoji: '<:coin_sky:1516859918739705887>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        bfusd:     { name: 'BFUSD',                  symbol: 'BFUSD',     emoji: '<:coin_bfusd:1516859927577100318>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://bscscan.com/address/', txExplorer: null },
        morpho:    { name: 'Morpho',                 symbol: 'MORPHO',    emoji: '<:coin_morpho:1516859931964346511>',    decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        bgb:       { name: 'Bitget Token',           symbol: 'BGB',       emoji: '<:coin_bgb:1516859938482290698>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        pepe:      { name: 'Pepe',                   symbol: 'PEPE',      emoji: '<:coin_pepe:1516859942815141898>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        aave:      { name: 'Aave',                   symbol: 'AAVE',      emoji: '<:coin_aave:1516859947349184695>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/token/0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9', txExplorer: null },
        etc:       { name: 'Ethereum Classic',       symbol: 'ETC',       emoji: '<:coin_etc:1516859952009052270>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://blockscout.com/etc/mainnet/address/', txExplorer: null },
        u:         { name: 'U',                      symbol: 'U',         emoji: '<:coin_u:1516859965367779378>',         decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        ustb:      { name: 'USTB',                   symbol: 'USTB',      emoji: '<:coin_ustb:1516859980912005204>',      decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        bcap:      { name: 'BCAP',                   symbol: 'BCAP',      emoji: '<:coin_bcap:1516859985685123122>',      decimals: 0,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        eutbl:     { name: 'eUTBL',                  symbol: 'eUTBL',     emoji: '<:coin_eutbl:1516859990529282250>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        usdtb:     { name: 'USDtb',                  symbol: 'USDtb',     emoji: '<:coin_usdtb:1516859994954535002>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        render:    { name: 'Render',                 symbol: 'RENDER',    emoji: '<:coin_render:1516859999538909305>',    decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        ena:       { name: 'Ethena',                 symbol: 'ENA',       emoji: '<:coin_ena:1516860012549378099>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        jtrsy:     { name: 'jTRSY',                  symbol: 'jTRSY',     emoji: '<:coin_jtrsy:1516860017813487821>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        nexo:      { name: 'Nexo',                   symbol: 'NEXO',      emoji: '<:coin_nexo:1516860027514650755>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        stable:    { name: 'Stable',                 symbol: 'STABLE',    emoji: '<:coin_stable:1516860031822332147>',    decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        vvv:       { name: 'Venice',                 symbol: 'VVV',       emoji: '<:coin_vvv:1516860036964417698>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        gt:        { name: 'Gate Token',             symbol: 'GT',        emoji: '<:coin_gt:1516860041196736684>',        decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        dexe:      { name: 'DeXe',                   symbol: 'DEXE',      emoji: '<:coin_dexe:1516860045499957310>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        jst:       { name: 'JUST',                   symbol: 'JST',       emoji: '<:coin_jst:1516860050059165797>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://tronscan.org/#/address/', txExplorer: null },
        jaaa:      { name: 'jAAA',                   symbol: 'jAAA',      emoji: '<:coin_jaaa:1516860054412722267>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        jup:       { name: 'Jupiter',                symbol: 'JUP',       emoji: '<:coin_jup:1516860068803383376>',       decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://solscan.io/account/', txExplorer: null },
        bdx:       { name: 'Beldex',                 symbol: 'BDX',       emoji: '<:coin_bdx:1516860077204701216>',       decimals: 12, tatumNetwork: null, addressType: null, explorer: 'https://explorer.beldex.io/', txExplorer: null },
        gho:       { name: 'GHO',                    symbol: 'GHO',       emoji: '<:coin_gho:1516860086746611722>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        usd0:      { name: 'USD0',                   symbol: 'USD0',      emoji: '<:coin_usd0:1516860106518564995>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        eursafo:   { name: 'eUROSAFO',               symbol: 'eURSAFO',   emoji: '<:coin_eursafo:1516860116765249718>',   decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        pump:      { name: 'Pump',                   symbol: 'PUMP',      emoji: '<:coin_pump:1516860121806802964>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://solscan.io/account/', txExplorer: null },
        night:     { name: 'Night',                  symbol: 'NIGHT',     emoji: '<:coin_night:1516860126471131146>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        a7a5:      { name: 'A7A5',                   symbol: 'A7A5',      emoji: '<:coin_a7a5:1516860134075142195>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        usx:       { name: 'USX',                    symbol: 'USX',       emoji: '<:coin_usx:1516860138705916066>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        beat:      { name: 'Beat',                   symbol: 'BEAT',      emoji: '<:coin_beat:1516860144527347795>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        aero:      { name: 'Aerodrome Finance',      symbol: 'AERO',      emoji: '<:coin_aero:1516860149254324366>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://basescan.org/address/', txExplorer: null },
        tusd:      { name: 'TrueUSD',                symbol: 'TUSD',      emoji: '<:coin_tusd:1516860153473929367>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        adi:       { name: 'ADI',                    symbol: 'ADI',       emoji: '<:coin_adi:1516860158276407306>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        ousg:      { name: 'OUSG',                   symbol: 'OUSG',      emoji: '<:coin_ousg:1516860255114625074>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        fet:       { name: 'Fetch.ai',               symbol: 'FET',       emoji: '<:coin_fet:1516860258222346471>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        lit:       { name: 'Litentry',               symbol: 'LIT',       emoji: '<:coin_lit:1516860264824176661>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        trump:     { name: 'Official Trump',         symbol: 'TRUMP',     emoji: '<:coin_trump:1516860272344830072>',     decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://solscan.io/account/', txExplorer: null },
        pengu:     { name: 'Pudgy Penguins',         symbol: 'PENGU',     emoji: '<:coin_pengu:1516860275532501082>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://solscan.io/account/', txExplorer: null },
        cake:      { name: 'PancakeSwap',            symbol: 'CAKE',      emoji: '<:coin_cake:1516860278757654701>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://bscscan.com/address/', txExplorer: null },
        eurc:      { name: 'EURC',                   symbol: 'EURC',      emoji: '<:coin_eurc:1516860291957395466>',      decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        kite:      { name: 'Kite',                   symbol: 'KITE',      emoji: '<:coin_kite:1516860298232070145>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        bonk:      { name: 'BONK',                   symbol: 'BONK',      emoji: '<:coin_bonk:1516860302862450831>',      decimals: 5,  tatumNetwork: null, addressType: null, explorer: 'https://solscan.io/account/', txExplorer: null },
        spx:       { name: 'SPX6900',                symbol: 'SPX',       emoji: '<:coin_spx:1516860307610271825>',       decimals: 8,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        virtual:   { name: 'Virtuals Protocol',      symbol: 'VIRTUAL',   emoji: '<:coin_virtual:1516860314333745172>',   decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://basescan.org/address/', txExplorer: null },
        prime:     { name: 'Echelon Prime',          symbol: 'PRIME',     emoji: '<:coin_prime:1516860327730348263>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        apxusd:    { name: 'apxUSD',                 symbol: 'apxUSD',    emoji: '<:coin_apxusd:1516860334487638177>',    decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        h:         { name: 'H',                      symbol: 'H',         emoji: '<:coin_h:1516860337620521072>',         decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        crv:       { name: 'Curve DAO Token',        symbol: 'CRV',       emoji: '<:coin_crv:1516860357921079348>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        jto:       { name: 'Jito',                   symbol: 'JTO',       emoji: '<:coin_jto:1516860371376537793>',       decimals: 9,  tatumNetwork: null, addressType: null, explorer: 'https://solscan.io/account/', txExplorer: null },
        fdusd:     { name: 'First Digital USD',      symbol: 'FDUSD',     emoji: '<:coin_fdusd:1516860378032902297>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://bscscan.com/address/', txExplorer: null },
        ethfi:     { name: 'Ether.fi',               symbol: 'ETHFI',     emoji: '<:coin_ethfi:1516860384580075663>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        '9bit':    { name: '9Bit',                   symbol: '9BIT',      emoji: '<:coin_9bit:1516860391437635704>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        skyai:     { name: 'SkyAI',                  symbol: 'SKYAI',     emoji: '<:coin_skyai:1516860398215889096>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        kau:       { name: 'Kinesis Gold',           symbol: 'KAU',       emoji: '<:coin_kau:1516860402363928749>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        sun:       { name: 'Sun Token',              symbol: 'SUN',       emoji: '<:coin_sun:1516860409443782878>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://tronscan.org/#/address/', txExplorer: null },
        pyth:      { name: 'Pyth Network',           symbol: 'PYTH',      emoji: '<:coin_pyth:1516860415810994266>',      decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://solscan.io/account/', txExplorer: null },
        grass:     { name: 'Grass',                  symbol: 'GRASS',     emoji: '<:coin_grass:1516860422169559193>',     decimals: 9,  tatumNetwork: null, addressType: null, explorer: 'https://solscan.io/account/', txExplorer: null },
        ub:        { name: 'UB',                     symbol: 'UB',        emoji: '<:coin_ub:1516860429018595569>',        decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        gno:       { name: 'Gnosis',                 symbol: 'GNO',       emoji: '<:coin_gno:1516860432898330635>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        zro:       { name: 'LayerZero',              symbol: 'ZRO',       emoji: '<:coin_zro:1516860445682827385>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        kag:       { name: 'Kinesis Silver',         symbol: 'KAG',       emoji: '<:coin_kag:1516860459314315425>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        nft:       { name: 'APENFT',                 symbol: 'NFT',       emoji: '<:coin_nft:1516860466146574365>',       decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://tronscan.org/#/address/', txExplorer: null },
        '2z':      { name: '2Z',                     symbol: '2Z',        emoji: '<:coin_2z:1516860472496754749>',        decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        btt:       { name: 'BitTorrent',             symbol: 'BTT',       emoji: '<:coin_btt:1516860478889132215>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://tronscan.org/#/address/', txExplorer: null },
        zbcn:      { name: 'Zebec Network',          symbol: 'ZBCN',      emoji: '<:coin_zbcn:1516860486036230275>',      decimals: 9,  tatumNetwork: null, addressType: null, explorer: 'https://solscan.io/account/', txExplorer: null },
        pendle:    { name: 'Pendle',                 symbol: 'PENDLE',    emoji: '<:coin_pendle:1516860492130422847>',    decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        chz:       { name: 'Chiliz',                 symbol: 'CHZ',       emoji: '<:coin_chz:1516860498845372426>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        floki:     { name: 'FLOKI',                  symbol: 'FLOKI',     emoji: '<:coin_floki:1516860505732419765>',     decimals: 9,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        jasmy:     { name: 'JasmyCoin',              symbol: 'JASMY',     emoji: '<:coin_jasmy:1516860513253064914>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        rusd:      { name: 'RUSD',                   symbol: 'RUSD',      emoji: '<:coin_rusd:1516860526502871140>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        ldo:       { name: 'Lido DAO',               symbol: 'LDO',       emoji: '<:coin_ldo:1516860529636020345>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        ohm:       { name: 'Olympus',                symbol: 'OHM',       emoji: '<:coin_ohm:1516860536023683162>',       decimals: 9,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        gwei:      { name: 'GWEI',                   symbol: 'GWEI',      emoji: '<:coin_gwei:1516860543653118052>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        frax:      { name: 'Frax',                   symbol: 'FRAX',      emoji: '<:coin_frax:1516860550196232323>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        tel:       { name: 'Telcoin',                symbol: 'TEL',       emoji: '<:coin_tel:1516860557607702741>',       decimals: 2,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        akt:       { name: 'Akash Network',          symbol: 'AKT',       emoji: '<:coin_akt:1516860564973031607>',       decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://www.mintscan.io/akash/address/', txExplorer: null },
        strk:      { name: 'Starknet',               symbol: 'STRK',      emoji: '<:coin_strk:1516860578360983583>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://starkscan.co/contract/', txExplorer: null },
        b:         { name: 'Beam',                   symbol: 'BEAM',      emoji: '<:coin_b:1516860584870674442>',         decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        coco:      { name: 'CoCo',                   symbol: 'COCO',      emoji: '<:coin_coco:1516860592101527693>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        apepe:     { name: 'Apepe',                  symbol: 'APEPE',     emoji: '<:coin_apepe:1516860600209113108>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        ff:        { name: 'FF',                     symbol: 'FF',        emoji: '<:coin_ff:1516860613274374205>',        decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        ens:       { name: 'Ethereum Name Service',  symbol: 'ENS',       emoji: '<:coin_ens:1516860619700174898>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        usdm:      { name: 'USDM',                   symbol: 'USDM',      emoji: '<:coin_usdm:1516860626436358254>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        koge:      { name: 'KogeDAO',                symbol: 'KOGE',      emoji: '<:coin_koge:1516860632920756264>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://bscscan.com/address/', txExplorer: null },
        usda:      { name: 'USDA',                   symbol: 'USDA',      emoji: '<:coin_usda:1516860646308712538>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        grt:       { name: 'The Graph',              symbol: 'GRT',       emoji: '<:coin_grt:1516860653535494305>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        real:      { name: 'Real',                   symbol: 'REAL',      emoji: '<:coin_real:1516860666332319815>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        crvusd:    { name: 'crvUSD',                 symbol: 'crvUSD',    emoji: '<:coin_crvusd:1516860672988942418>',    decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        pc0000031: { name: 'PC0000031',              symbol: 'PC31',      emoji: '<:coin_pc0000031:1516860679120879729>', decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        pieverse:  { name: 'PieVerse',               symbol: 'PIEVERSE',  emoji: '<:coin_pieverse:1516860685240238291>',  decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        usdai:     { name: 'USDai',                  symbol: 'USDai',     emoji: '<:coin_usdai:1516860688641822861>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        onyc:      { name: 'ONYC',                   symbol: 'ONYC',      emoji: '<:coin_onyc:1516860694967095296>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        usat:      { name: 'USAT',                   symbol: 'USAT',      emoji: '<:coin_usat:1516860701329723444>',      decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        ultima:    { name: 'Ultima',                 symbol: 'ULTIMA',    emoji: '<:coin_ultima:1516860707969302538>',    decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        apyusd:    { name: 'apyUSD',                 symbol: 'apyUSD',    emoji: '<:coin_apyusd:1516860714537455626>',    decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        nex:       { name: 'Nash',                   symbol: 'NEX',       emoji: '<:coin_nex:1516860720686436542>',       decimals: 8,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        btse:      { name: 'BTSE Token',             symbol: 'BTSE',      emoji: '<:coin_btse:1516860727414096113>',      decimals: 8,  tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        axs:       { name: 'Axie Infinity',          symbol: 'AXS',       emoji: '<:coin_axs:1516860734355542206>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        syrup:     { name: 'Syrup',                  symbol: 'SYRUP',     emoji: '<:coin_syrup:1516860740840194148>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        comp:      { name: 'Compound',               symbol: 'COMP',      emoji: '<:coin_comp:1516860746812887154>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        wfi:       { name: 'WFI',                    symbol: 'WFI',       emoji: '<:coin_wfi:1516860753645273098>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        reusd:     { name: 'reUSD',                  symbol: 'reUSD',     emoji: '<:coin_reusd:1516860795080671242>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        wif:       { name: 'dogwifhat',              symbol: 'WIF',       emoji: '<:coin_wif:1516860801405816993>',       decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://solscan.io/account/', txExplorer: null },
        twt:       { name: 'Trust Wallet Token',     symbol: 'TWT',       emoji: '<:coin_twt:1516860807663587409>',       decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://bscscan.com/address/', txExplorer: null },
        ray:       { name: 'Raydium',                symbol: 'RAY',       emoji: '<:coin_ray:1516860814265417779>',       decimals: 6,  tatumNetwork: null, addressType: null, explorer: 'https://solscan.io/account/', txExplorer: null },
        mx:        { name: 'MX Token',               symbol: 'MX',        emoji: '<:coin_mx:1516860820619919600>',        decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        bill:      { name: 'Bill',                   symbol: 'BILL',      emoji: '<:coin_bill:1516860827045462096>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        rail:      { name: 'Rail',                   symbol: 'RAIL',      emoji: '<:coin_rail:1516860833341112320>',      decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
        ustbl:     { name: 'USTBL',                  symbol: 'USTBL',     emoji: '<:coin_ustbl:1516860853075316848>',     decimals: 18, tatumNetwork: null, addressType: null, explorer: 'https://etherscan.io/address/', txExplorer: null },
};

export const CHAIN_ALIASES = {
        ethereum: 'eth',
        bitcoin: 'btc',
        solana: 'sol',
        bnbchain: 'bnb',
        bsc: 'bnb',
        'bnb chain': 'bnb',
        polygon: 'pol',
        matic: 'pol',
        tron: 'trx',
        stellar: 'xlm',
        ripple: 'xrp',
        litecoin: 'ltc',
        bitcoincash: 'bch',
        'bitcoin cash': 'bch',
        dogecoin: 'doge',
        zcash: 'zec',
        tezos: 'xtz',
        avalanche: 'avax',
        algorand: 'algo',
        cardano: 'ada',
        monero: 'xmr',
        polkadot: 'dot',
        arbitrum: 'arb',
        optimism: 'op',
        injective: 'inj',
        aptos: 'apt',
        mantle: 'mnt',
        hedera: 'hbar',
        kucoin: 'kcs',
        cronos: 'cro',
        klaytn: 'kaia',
        flare: 'flr',
};

/**
 * Resolve a user-supplied chain string to a CHAINS entry.
 * Returns null if not found.
 * @param {string} input
 * @returns {(typeof CHAINS[string] & { key: string }) | null}
 */
export function resolveChain(input) {
        if (!input) return null;
        const key = input.toLowerCase().trim().replace(/\s+/g, '');
        const direct = CHAINS[key];
        if (direct) return { ...direct, key };
        const aliased = CHAIN_ALIASES[key] || CHAIN_ALIASES[input.toLowerCase().trim()];
        if (aliased && CHAINS[aliased]) return { ...CHAINS[aliased], key: aliased };
        return null;
}
