export const CHAINS = {
        btc: {
                name: 'Bitcoin',
                symbol: 'BTC',
                emoji: '<:coin_btc:1516859667093917877>',
                decimals: 8,
                tatumNetwork: 'bitcoin',
                addressType: 'utxo',
                explorer: 'https://blockchair.com/bitcoin/address/',
                txExplorer: 'https://blockchair.com/bitcoin/transaction/',
        },
        eth: {
                name: 'Ethereum',
                symbol: 'ETH',
                emoji: '<:coin_eth:1516859671057666071>',
                decimals: 18,
                tatumNetwork: 'ethereum',
                addressType: 'evm',
                explorer: 'https://etherscan.io/address/',
                txExplorer: 'https://etherscan.io/tx/',
        },
        ltc: {
                name: 'Litecoin',
                symbol: 'LTC',
                emoji: '<:coin_ltc:1516859796731461663>',
                decimals: 8,
                tatumNetwork: 'litecoin',
                addressType: 'utxo',
                explorer: 'https://blockchair.com/litecoin/address/',
                txExplorer: 'https://blockchair.com/litecoin/transaction/',
        },
        bch: {
                name: 'Bitcoin Cash',
                symbol: 'BCH',
                emoji: '<:coin_bch:1516859774195728516>',
                decimals: 8,
                tatumNetwork: 'bcash',
                addressType: 'utxo',
                explorer: 'https://blockchair.com/bitcoin-cash/address/',
                txExplorer: 'https://blockchair.com/bitcoin-cash/transaction/',
        },
        doge: {
                name: 'Dogecoin',
                symbol: 'DOGE',
                emoji: '<:coin_doge:1516859711746736191>',
                decimals: 8,
                tatumNetwork: 'dogecoin',
                addressType: 'utxo',
                explorer: 'https://blockchair.com/dogecoin/address/',
                txExplorer: 'https://blockchair.com/dogecoin/transaction/',
        },
        zec: {
                name: 'Zcash',
                symbol: 'ZEC',
                emoji: '<:coin_zec:1516859729832316999>',
                decimals: 8,
                tatumNetwork: 'zcash',
                addressType: 'utxo',
                explorer: 'https://blockchair.com/zcash/address/',
                txExplorer: 'https://blockchair.com/zcash/transaction/',
        },
        dash: {
                name: 'Dash',
                symbol: 'DASH',
                emoji: '<:coin_dash:1516860162877690027>',
                decimals: 8,
                tatumNetwork: 'dash',
                addressType: 'utxo',
                explorer: 'https://blockchair.com/dash/address/',
                txExplorer: 'https://blockchair.com/dash/transaction/',
        },
        xrp: {
                name: 'XRP',
                symbol: 'XRP',
                emoji: '<:coin_xrp:1516859684672372831>',
                decimals: 6,
                tatumNetwork: 'xrp',
                addressType: 'xrp',
                explorer: 'https://xrpscan.com/account/',
                txExplorer: 'https://xrpscan.com/tx/',
        },
        xlm: {
                name: 'Stellar',
                symbol: 'XLM',
                emoji: '<:coin_xlm:1516859734379069722>',
                decimals: 7,
                tatumNetwork: 'xlm',
                addressType: 'xlm',
                explorer: 'https://stellar.expert/explorer/public/account/',
                txExplorer: 'https://stellar.expert/explorer/public/tx/',
        },
        trx: {
                name: 'Tron',
                symbol: 'TRX',
                emoji: '<:coin_trx:1516859698245271732>',
                decimals: 6,
                tatumNetwork: 'tron',
                addressType: 'tron',
                explorer: 'https://tronscan.org/#/address/',
                txExplorer: 'https://tronscan.org/#/transaction/',
        },
        sol: {
                name: 'Solana',
                symbol: 'SOL',
                emoji: '<:coin_sol:1516859693950042212>',
                decimals: 9,
                tatumNetwork: 'solana',
                addressType: 'solana',
                explorer: 'https://solscan.io/account/',
                txExplorer: 'https://solscan.io/tx/',
        },
        bnb: {
                name: 'BNB Chain',
                symbol: 'BNB',
                emoji: '<:coin_bnb:1516859680289460287>',
                decimals: 18,
                tatumNetwork: 'bsc',
                addressType: 'evm',
                explorer: 'https://bscscan.com/address/',
                txExplorer: 'https://bscscan.com/tx/',
        },
        pol: {
                name: 'Polygon',
                symbol: 'POL',
                emoji: '<:coin_pol:1516860022683078787>',
                decimals: 18,
                tatumNetwork: 'polygon',
                addressType: 'evm',
                explorer: 'https://polygonscan.com/address/',
                txExplorer: 'https://polygonscan.com/tx/',
        },
        avax: {
                name: 'Avalanche',
                symbol: 'AVAX',
                emoji: '<:coin_avax:1516859814540742886>',
                decimals: 18,
                tatumNetwork: 'avax',
                addressType: 'evm',
                explorer: 'https://snowtrace.io/address/',
                txExplorer: 'https://snowtrace.io/tx/',
        },
        algo: {
                name: 'Algorand',
                symbol: 'ALGO',
                emoji: '<:coin_algo:1516860003850522745>',
                decimals: 6,
                tatumNetwork: 'algorand',
                addressType: 'algorand',
                explorer: 'https://algoexplorer.io/address/',
                txExplorer: 'https://algoexplorer.io/tx/',
        },
        ada: {
                name: 'Cardano',
                symbol: 'ADA',
                emoji: '<:coin_ada:1516859747964551178>',
                decimals: 6,
                tatumNetwork: 'ada',
                addressType: 'ada',
                explorer: 'https://cardanoscan.io/address/',
                txExplorer: 'https://cardanoscan.io/transaction/',
        },
        xtz: {
                name: 'Tezos',
                symbol: 'XTZ',
                emoji: '<:coin_xtz:1516860452569616404>',
                decimals: 6,
                tatumNetwork: 'tezos',
                addressType: 'tezos',
                explorer: 'https://tzstats.com/',
                txExplorer: 'https://tzstats.com/',
        },
        xmr: {
                name: 'Monero',
                symbol: 'XMR',
                emoji: '<:coin_xmr:1516859752674758795>',
                decimals: 12,
                tatumNetwork: null,
                addressType: null,
                explorer: 'https://xmrchain.net/search?value=',
                txExplorer: 'https://xmrchain.net/tx/',
        },
        dot: {
                name: 'Polkadot',
                symbol: 'DOT',
                emoji: '<:coin_dot:1516859887131427040>',
                decimals: 10,
                tatumNetwork: 'dot',
                addressType: 'substrate',
                explorer: 'https://polkadot.subscan.io/account/',
                txExplorer: 'https://polkadot.subscan.io/extrinsic/',
        },
        near: {
                name: 'NEAR',
                symbol: 'NEAR',
                emoji: '<:coin_near:1516859810170015744>',
                decimals: 24,
                tatumNetwork: 'near',
                addressType: 'near',
                explorer: 'https://nearblocks.io/address/',
                txExplorer: 'https://nearblocks.io/txns/',
        },
        flr: {
                name: 'Flare',
                symbol: 'FLR',
                emoji: '<:coin_flr:1516860063942443088>',
                decimals: 18,
                tatumNetwork: 'flare',
                addressType: 'evm',
                explorer: 'https://flare-explorer.flare.network/address/',
                txExplorer: 'https://flare-explorer.flare.network/tx/',
        },
        kaia: {
                name: 'Kaia',
                symbol: 'KAIA',
                emoji: '<:coin_kaia:1516860606886580414>',
                decimals: 18,
                tatumNetwork: 'klaytn',
                addressType: 'evm',
                explorer: 'https://kaiascope.com/address/',
                txExplorer: 'https://kaiascope.com/tx/',
        },
        cro: {
                name: 'Cronos',
                symbol: 'CRO',
                emoji: '<:coin_cro:1516859823612887111>',
                decimals: 18,
                tatumNetwork: 'cro',
                addressType: 'evm',
                explorer: 'https://cronoscan.com/address/',
                txExplorer: 'https://cronoscan.com/tx/',
        },
        arb: {
                name: 'Arbitrum',
                symbol: 'ARB',
                emoji: '<:coin_arb:1516860096791969933>',
                decimals: 18,
                tatumNetwork: 'arbitrum',
                addressType: 'evm',
                explorer: 'https://arbiscan.io/address/',
                txExplorer: 'https://arbiscan.io/tx/',
        },
        op: {
                name: 'Optimism',
                symbol: 'OP',
                emoji: '<:coin_op:1516860571763478578>',
                decimals: 18,
                tatumNetwork: 'optimism',
                addressType: 'evm',
                explorer: 'https://optimistic.etherscan.io/address/',
                txExplorer: 'https://optimistic.etherscan.io/tx/',
        },
        inj: {
                name: 'Injective',
                symbol: 'INJ',
                emoji: '<:coin_inj:1516860110650216500>',
                decimals: 18,
                tatumNetwork: 'inj',
                addressType: 'evm',
                explorer: 'https://explorer.injective.network/account/',
                txExplorer: 'https://explorer.injective.network/transaction/',
        },
        sui: {
                name: 'Sui',
                symbol: 'SUI',
                emoji: '<:coin_sui:1516859800850530327>',
                decimals: 9,
                tatumNetwork: 'sui',
                addressType: 'sui',
                explorer: 'https://suivision.xyz/address/',
                txExplorer: 'https://suivision.xyz/txblock/',
        },
        apt: {
                name: 'Aptos',
                symbol: 'APT',
                emoji: '<:coin_apt:1516860090966212629>',
                decimals: 8,
                tatumNetwork: 'aptos',
                addressType: 'aptos',
                explorer: 'https://aptoscan.com/account/',
                txExplorer: 'https://aptoscan.com/transaction/',
        },
        sei: {
                name: 'Sei',
                symbol: 'SEI',
                emoji: '<:coin_sei:1516860350836768930>',
                decimals: 6,
                tatumNetwork: 'sei',
                addressType: 'sei',
                explorer: 'https://seistream.app/address/',
                txExplorer: 'https://seistream.app/tx/',
        },
        mnt: {
                name: 'Mantle',
                symbol: 'MNT',
                emoji: '<:coin_mnt:1516859882265903107>',
                decimals: 18,
                tatumNetwork: 'mantle',
                addressType: 'evm',
                explorer: 'https://mantlescan.xyz/address/',
                txExplorer: 'https://mantlescan.xyz/tx/',
        },
        hbar: {
                name: 'Hedera',
                symbol: 'HBAR',
                emoji: '<:coin_hbar:1516859792373710848>',
                decimals: 8,
                tatumNetwork: 'hbar',
                addressType: 'hbar',
                explorer: 'https://hashscan.io/mainnet/account/',
                txExplorer: 'https://hashscan.io/mainnet/transaction/',
        },
        kcs: {
                name: 'KuCoin',
                symbol: 'KCS',
                emoji: '<:coin_kcs:1516859969763541175>',
                decimals: 18,
                tatumNetwork: 'kcs',
                addressType: 'evm',
                explorer: 'https://explorer.kcc.io/address/',
                txExplorer: 'https://explorer.kcc.io/tx/',
        },
};

export const CHAIN_ALIASES = {
        ethereum: 'eth',
        bitcoin: 'btc',
        solana: 'sol',
        bnbchain: 'bnb',
        bsc: 'bnb',
        'bnb chain': 'bnb',
        polygon: 'pol',
        matic: 'pol',
        tron: 'trx',
        stellar: 'xlm',
        ripple: 'xrp',
        litecoin: 'ltc',
        bitcoincash: 'bch',
        'bitcoin cash': 'bch',
        dogecoin: 'doge',
        zcash: 'zec',
        tezos: 'xtz',
        avalanche: 'avax',
        algorand: 'algo',
        cardano: 'ada',
        monero: 'xmr',
        polkadot: 'dot',
        arbitrum: 'arb',
        optimism: 'op',
        injective: 'inj',
        aptos: 'apt',
        mantle: 'mnt',
        hedera: 'hbar',
        kucoin: 'kcs',
        cronos: 'cro',
        klaytn: 'kaia',
        flare: 'flr',
};

/**
 * Resolve a user-supplied chain string to a CHAINS entry.
 * Returns null if not found.
 * @param {string} input
 * @returns {(typeof CHAINS[string] & { key: string }) | null}
 */
export function resolveChain(input) {
        if (!input) return null;
        const key = input.toLowerCase().trim().replace(/\s+/g, '');
        const direct = CHAINS[key];
        if (direct) return { ...direct, key };
        const aliased = CHAIN_ALIASES[key] || CHAIN_ALIASES[input.toLowerCase().trim()];
        if (aliased && CHAINS[aliased]) return { ...CHAINS[aliased], key: aliased };
        return null;
}
